"""Async client for OpenWrt's ubus HTTP/JSON-RPC API."""

from ._parse import normalize_mac
from .client import UbusClient
from .const import (
    DEFAULT_PATH,
    DEFAULT_SESSION_TIMEOUT,
    DEFAULT_TIMEOUT,
    NULL_SESSION_ID,
    JsonRpcError,
    UbusStatus,
)
from .exceptions import (
    UbusAuthenticationError,
    UbusCallError,
    UbusConnectionError,
    UbusError,
    UbusHttpError,
    UbusInvalidArgumentError,
    UbusMethodNotFoundError,
    UbusNoDataError,
    UbusNotFoundError,
    UbusNotSupportedError,
    UbusObjectNotFoundError,
    UbusPermissionError,
    UbusResponseError,
    UbusSSLError,
    UbusTimeoutError,
)
from .models import (
    BoardJson,
    DhcpLease,
    DnsmasqLease,
    HostapdClient,
    HostapdClients,
    HostHint,
    InterfaceAddress,
    NetworkDevice,
    OdhcpdLease,
    ReleaseInfo,
    SessionInfo,
    SystemBoard,
    UciSection,
    UciValue,
    WirelessInterface,
    WirelessRadio,
    parse_dnsmasq_leases,
)

__version__ = "0.1.0"

__all__ = [
    "DEFAULT_PATH",
    "DEFAULT_SESSION_TIMEOUT",
    "DEFAULT_TIMEOUT",
    "NULL_SESSION_ID",
    "BoardJson",
    "DhcpLease",
    "DnsmasqLease",
    "HostHint",
    "HostapdClient",
    "HostapdClients",
    "InterfaceAddress",
    "JsonRpcError",
    "NetworkDevice",
    "OdhcpdLease",
    "ReleaseInfo",
    "SessionInfo",
    "SystemBoard",
    "UbusAuthenticationError",
    "UbusCallError",
    "UbusClient",
    "UbusConnectionError",
    "UbusError",
    "UbusHttpError",
    "UbusInvalidArgumentError",
    "UbusMethodNotFoundError",
    "UbusNoDataError",
    "UbusNotFoundError",
    "UbusNotSupportedError",
    "UbusObjectNotFoundError",
    "UbusPermissionError",
    "UbusResponseError",
    "UbusSSLError",
    "UbusStatus",
    "UbusTimeoutError",
    "UciSection",
    "UciValue",
    "WirelessInterface",
    "WirelessRadio",
    "normalize_mac",
    "parse_dnsmasq_leases",
]
